In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
import warnings
warnings.filterwarnings('ignore')
digit = load_digits()


In [2]:
dir(digit)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digit.data, digit.target, test_size = 0.3)

In [4]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9518518518518518

In [5]:
svm = SVC() 
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.987037037037037

In [6]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9740740740740741

In [36]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5)

In [37]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


In [38]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [39]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

0.9148580968280468

In [40]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=5)

In [41]:
score_lr = []
score_svm = []
score_rf = []

for train_index, test_index in kf.split(digit.data):
    X_train, X_test, y_train, y_test = digit.data[train_index], digit.data[test_index], \
                                       digit.target[train_index], digit.target[test_index]
    score_lr.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    score_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [43]:
data = [score_lr, score_svm, score_rf]
score_final = pd.DataFrame(data = data)
score_final.columns = ['Fold 1', ' Fold 2', 'Fold 3', 'Fold 4', 'Fold 5']
score_final.index = ['Linear Regression', 'SVM', 'Random Forest']

In [44]:
score_final

Fold 1    Fold 2    Fold 3    Fold 4    Fold 5
Linear Regression  0.927778  0.866667  0.938719  0.935933  0.908078
SVM                0.969444  0.947222  0.983287  0.988858  0.941504
Random Forest      0.930556  0.897222  0.961003  0.952646  0.924791

In [34]:
from sklearn.model_selection import cross_val_score

In [35]:
cross_val_score(LogisticRegression(), digit.data, digit.target)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [46]:
cross_val_score(SVC(), digit.data, digit.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [49]:
cross_val_score(RandomForestClassifier(n_estimators=40), digit.data, digit.target)

array([0.94166667, 0.88888889, 0.94707521, 0.95821727, 0.93036212])