In [1]:
import numpy as np

## Creating Numpy Arrays from Python Lists

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
[3.14, 4,2,3]

[3.14, 4, 2, 3]

In [4]:
np.array([3.14, 4, 5, 6]) #convert sang kieu du lieu lon hon

array([3.14, 4.  , 5.  , 6.  ])

In [5]:
#cụ thể hóa kiểu dữ liệu mảng cần
np.array([1,2,3,4], dtype = "float32")

array([1., 2., 3., 4.], dtype=float32)

In [6]:
a1 = np.array([1,2,3,4])

In [7]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3],
              [4,5,6]])

In [9]:
type(a2)

numpy.ndarray

In [10]:
a2.shape

(2, 3)

In [11]:
a2.ndim # số chiều của mảng

2

In [12]:
a2.size #tổng element trong mảng

6

## Creating Numpy Arrays from Scratch
- zeros, ones, full, arange, linspace
- shift tab

In [13]:
# zeros dung de tao mang toàn là số 0
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
# ones dung de tao mang toan la so 1
np.ones([3,5], dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# arange tạo mảng từ bao nhiu đến bao nhiêu
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
# full, tạo mảng np fill theo ý mình muốn
np.full([3,5], 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [17]:
#linspace, tạo khoảng cách nhau 1 cách tuyến tính
np.linspace(0, 1, 5) # khoang tu 0 den 1, chia deu lam 5

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## random

In [18]:
# seed for preproducibility: các giá trị ngẫu nhiên chạy bao nhiêu lần đều ra cùng một kết quả
np.random.seed(0)

np.random.random((4,4)) # nam trong khoang tu 0 den 1

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [19]:
np.random.rand(4,4) # chức năng tương tự np.random.random()

array([[0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369]])

In [20]:
np.random.normal(0,1, (3,3)) # mean, độ lệch chuẩn (Standard Deviation), size

array([[ 2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575]])

In [21]:
np.random.randint(1, 20, (3,3)) # random các số nguyên ngẫu nhiên

array([[ 2,  8, 10],
       [ 4,  7, 12],
       [15, 19,  1]])

## Array Indexing & Slicing
- One-dimensional subarray
- Cách tiếp cận các thành phần trong array

In [22]:
x1 = np.random.randint(20, size = 6)

In [23]:
x1

array([14,  3, 12, 10, 11,  4])

In [24]:
x1[4], x1[0], x1[-1]

(11, 14, 4)

## Multi-dimensional array

In [25]:
x2 = np.random.randint(10, size = (3,4))

In [26]:
x2

array([[6, 4, 4, 3],
       [4, 4, 8, 4],
       [3, 7, 5, 5]])

In [27]:
x2[1,2] = 5
x2

array([[6, 4, 4, 3],
       [4, 4, 5, 4],
       [3, 7, 5, 5]])

## Slicing:
x[start:stop:step]

In [28]:
x1

array([14,  3, 12, 10, 11,  4])

In [29]:
x1[0:3:1]

array([14,  3, 12])

In [40]:
x1[2:4]

array([12, 10])

In [41]:
# every other element, every 2 step
x1[::2]

array([14, 12, 11])

In [42]:
x2

array([[6, 4, 4, 3],
       [4, 4, 5, 4],
       [3, 7, 5, 5]])

In [44]:
# two rows, three columns
# 3 cột đầu tiên, 2 dòng của 3 cột đầu tiên
x2[:2, :3]

array([[6, 4, 4],
       [4, 4, 5]])

In [45]:
 x2[:, :2]

array([[6, 4],
       [4, 4],
       [3, 7]])

## Reshaping of Array & Transpose

In [47]:
grid = np.arange(1,10)
grid.shape

(9,)

In [48]:
# chuyen thanh ma tran 3x3
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
x = np.array([1,2,3])
x.shape

(3,)

In [50]:
x.reshape((1,3)).shape

(1, 3)

In [53]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [54]:
# transpose: chuyển hàng thành cột
x.T

array([[1, 3],
       [2, 4]])

## Array Concatenation and Spliting

In [55]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [56]:
# nối 2 array lại 
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [57]:
grid = np.array([[1,2,3],
                 [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.concatenate((grid, grid), axis = 1)
# axis = 1 noi theo column
# axis = 0 noi theo chieu row

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [62]:
#vstack: noi theo chieu column
x = np.array([1, 2, 3])
grid = np.array([[9,8,7],
                 [6,5,4]])
np.vstack((x, grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [65]:
# horizontally stack the arrays: hstack
y = np.array([[99],
             [99]])
np.hstack((y, grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

## Spliting of arrays

In [66]:
x = np.array([1,2,3,99,69,3,2,1])

In [69]:
x1, x2, x3 = np.split(x, [3,5])

In [72]:
x1

array([1, 2, 3])

In [73]:
x2

array([99, 69])

In [74]:
x3

array([3, 2, 1])

## Broadcasting and Vectorized operations
Broadcasting is simply a set of rules for applying binary ufuncs (e.g. addition, subtraction, multiplication, etc.) on arrays of different sizes.

In [75]:
a = np.array([0, 1, 2])

In [76]:
a

array([0, 1, 2])

In [77]:
a + 5 #broadcasting

array([5, 6, 7])

In [81]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [82]:
a.shape, b.shape

((3,), (3, 3))

In [83]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [92]:
c = np.arange(3).reshape((3,1))
c

array([[0],
       [1],
       [2]])

In [93]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Manipulatin & Comparing Arrays
### Aggregation
performing the same operation on a number of things

In [94]:
list_number = [1,2,3]

In [97]:
ll = np.array(list_number)
ll

array([1, 2, 3])

In [98]:
sum(ll) #Python sum()

6

In [99]:
np.sum(ll) #Numpy sum()

6

In [100]:
# Create a massive Numpy array
massive_array = np.random.rand(10000)

In [103]:
massive_array[:5]
massive_array.shape

(10000,)

In [104]:
# %timeit: thời gian dung để tính toán hàm thực hiện
%timeit sum(massive_array) # Python sum()
%timeit np.sum(massive_array) # Numpy sum()

797 µs ± 5.59 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
5.54 µs ± 71.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [105]:
np.mean(massive_array)

0.5013703974364666

In [106]:
np.max(massive_array)

0.9999709462497284

In [107]:
np.min(massive_array)

2.0027530115096503e-05

# Standard Deviation and Variance
- Độ lệch chuẩn: Đo độ phân tán so với mean
- Phương sai

In [109]:
dog_height = np.array([600, 470, 170, 430, 300]) 

In [110]:
np.std(dog_height) #do lech chuan

147.32277488562318

In [111]:
np.var(dog_height)

21704.0

In [112]:
np.sqrt(np.var(dog_height))

147.32277488562318

## Sorting Arrays
np.sort uses an quicksort algorithm

In [113]:
x = np.array([2,1,4,3,5])

In [114]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [116]:
np.argsort(x) # sap xep theo index cua tung element

array([1, 0, 3, 2, 4], dtype=int64)

In [118]:
np.random.seed(42)

MatA = np.random.randint(0, 10, size = (4, 6))

In [119]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [121]:
np.sort(MatA, axis = 0) #sap xep theo cot

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [122]:
np.sort(MatA, axis = 1) #sap xep theo hang

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## Linear Algebra
Đại số tuyến tính

In [123]:
A = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

In [124]:
B = np.array([[6,5],
              [4,3],
              [2,1]])

In [126]:
#A (3x3) dot product B(3x2): Tích vô hướng
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [127]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [128]:
# B(3x2) dot A(3x3): phai transpse B laij thanh 2x3 moi nhan dc
B.T.dot(A)

array([[36, 48, 60],
       [24, 33, 42]])

## Dot Product Example

In [129]:
# Number of jars sold
np.random.seed(0)

sale_amounts = np.random.randint(0, 20, size = (5, 3))

In [130]:
sale_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [132]:
# Creat weekly_sales DataFrame
import pandas as pd
weekly_sales = pd.DataFrame(sale_amounts, index = ["Mon", "Tues", "Wed", "Thus", "Fri"],
                                           columns = ["Almon Butter", "Peanut Butter", "Cashew Butter"] )

In [133]:
weekly_sales

Almon Butter  Peanut Butter  Cashew Butter
Mon             12             15              0
Tues             3              3              7
Wed              9             19             18
Thus             4              6             12
Fri              1              6              7

In [150]:
# creat a price array
prices = np.array([10,8,12])

In [151]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index = ["Prices"],
                                     columns = ["Almon Butter", "Peanut Butter", "Cashew Butter"])
# reshape no lai

In [152]:
butter_prices

Almon Butter  Peanut Butter  Cashew Butter
Prices            10              8             12

In [153]:
weekly_sales.shape, butter_prices.T.shape

((5, 3), (3, 1))

In [156]:
total_prices = weekly_sales.dot(butter_prices.T)

In [157]:
total_prices

Prices
Mon      240
Tues     138
Wed      458
Thus     232
Fri      142

In [159]:
weekly_sales["Total_prices"] = total_prices

In [160]:
weekly_sales

Almon Butter  Peanut Butter  Cashew Butter  Total_prices
Mon             12             15              0           240
Tues             3              3              7           138
Wed              9             19             18           458
Thus             4              6             12           232
Fri              1              6              7           142